#pod with security context : user 1001
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  securityContext:
    runAsUser: 1001 #set the user as 1001 in the pod
  containers:
    - image: ubuntu
      name: web
      command: ["sleep", "5000"]
      securityContext:
        runAsUser: 1002 #overwrite the user in the container level

    - image: ubuntu
      name: sidecar
      command: ["sleep", "5000"]

---
#Add capabilities to root user in the container
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - image: ubuntu
      name: web
      command: ["sleep", "5000"]
      securityContext:
        capabilities:
          add: ["SYS_TIME", "NET_Admin"]
