#a headless service is created like a normal service but the type should be none
# it does not have a clusterIP as normal service. it doesn't perfome any loadbalancing.
#all it does, it created dns entries for each pods using pod name and subdomain like:
# podname.headless-servicename.namespace.svc.cluster-domain => mysql-0.mysql-h.default.svc.cluster.local,
# mysql-1.mysql-h.default.svc.cluster.local, mysql-2.mysql-h.default.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: mysql-h
spec:
  clusterIP: None
  ports:
    - port: 3306
  selector:
    app: mysql #this is that connect the service and the pod
