#persistent volume. the persistent volume is create by and admin. the value will be stored in the host
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-v11
spec:
  accessModes: #the access mode defines how the data should mounted on the host: readOnlyMany, ReadWriteOnce, readWriteMany
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath: #do not do that on prod env
    path: /tmp/data
  persistentVolumeReclaimPolicy: Retain #If the pvc is deleted. the data will remain but not available for resuse by other claims

---
#persistent volume with aws elastic block store
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-v11
spec:
  accessModes: #the access mode defines how the data should mounted on the host: readOnlyMany, ReadWriteOnce, readWriteMany
    - ReadWriteOnce
  capacity:
    storage: 1Gi

  awsElasticBlockStore: #the rigth way to store persistent volume
  volumeID: <volume-id>
  fsType: ext4
