#secret definition ressource
apiVersion: v1
kind: Secret
metadata:
  name: app-config
data:
  DB_HOST: mysql # this value should be base64 encoded
  DB_USER: root # this value should be base64 encoded
  DB_PASSWORD: password # this value should be base64 encoded

---
#create pod with secret
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret

---
#secrets in pod(single env)
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD

---
#secrets in pod(volume)
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      volumes:
        - name: app-secret-volume
          secret:
            secretName: app-secret
