#limit range can help you define default values to be set for containers with in a pod

apiVersion: v1
kind: LimitRange
metadata:
  name: memory-ressource-constraint
spec:
  limits:
    - default:
        memory: 1Gi
      defaultRequest:
        memory: 1Gi
      max:
        memory: 1Gi
      min:
        memory: 500Mi
      type: container
